- name: Install apt packages
  apt: pkg={{ item }} state=present update_cache=true cache_valid_time=3600
  with_items: [build-essential, python-dev, python-pip]
  sudo: yes

- name: Install virtualenv version ({{ virtualenv_version }})
  command: pip install virtualenv=={{ virtualenv_version }}
  sudo: yes
  when: virtualenv_version is defined

- name: Install latest virtualenv version
  command: pip install virtualenv
  sudo: yes
  when: virtualenv_version is not defined

- name: Create folder for virtualenv
  file: state=directory owner={{ virtualenv_user }} group={{ virtualenv_group }} path={{ virtualenv_path }}
  sudo: yes

- name: Check whether virtualenv exists
  stat: path="{{ virtualenv_path }}/bin/activate"
  register: virtualenv_activate

- name: Create the virtualenv
  command: virtualenv {{ virtualenv_path }} --distribute {{ virtualenv_site_packages }}
  sudo: yes
  sudo_user: "{{ virtualenv_user }}"
  when: virtualenv_activate.stat.exists != true

- name: Reinstall pip version ({{ virtualenv_pip_version }})
  pip: name=pip version={{ virtualenv_pip_version }} virtualenv={{ virtualenv_path }}
  sudo: yes
  sudo_user: "{{ virtualenv_user }}"
  when: virtualenv_pip_version is defined

- name: Install requirements
  pip: requirements={{ virtualenv_requirements_file }} virtualenv={{ virtualenv_path }} extra_args='--process-dependency-links'
  sudo: yes
  sudo_user: "{{ virtualenv_user }}"
  when: virtualenv_requirements_file is defined
